# Generated by Django 5.0.2 on 2024-02-13 07:47

import cbv_advanced.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_todo_description_todo_slug_todo_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=models.SlugField(default=cbv_advanced.web.models.generate_slug, editable=False, max_length=28, unique=True),
        ),
    ]
