# Generated by Django 5.0.2 on 2024-02-19 19:36

import django.core.validators
import exam_doncho.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), exam_doncho.profiles.validators.validate_username]),
        ),
    ]
