# Generated by Django 5.0.1 on 2024-01-31 20:48

import django.core.validators
import django.db.models.deletion
import forms_advanced_demos.web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, validators=[forms_advanced_demos.web.models.validate_first_name, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.PositiveSmallIntegerField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='web/profile_images')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
